//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCarShopInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfCarShopInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Addresses.
        /// </summary>
        public static string Address_INDEX {
            get {
                return ResourceManager.GetString("Address_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address Types.
        /// </summary>
        public static string AddressType_INDEX {
            get {
                return ResourceManager.GetString("AddressType_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Articles by Group.
        /// </summary>
        public static string Article2Category {
            get {
                return ResourceManager.GetString("Article2Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Article Appliece.
        /// </summary>
        public static string ArticleApplic {
            get {
                return ResourceManager.GetString("ArticleApplic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Article Brand.
        /// </summary>
        public static string ArticleBrand {
            get {
                return ResourceManager.GetString("ArticleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Analogous.
        /// </summary>
        public static string ArticleLookUp {
            get {
                return ResourceManager.GetString("ArticleLookUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TecDoc Articles.
        /// </summary>
        public static string ArticleTecDoc {
            get {
                return ResourceManager.GetString("ArticleTecDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enterprise Articules.
        /// </summary>
        public static string ArticuleTree {
            get {
                return ResourceManager.GetString("ArticuleTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Axles.
        /// </summary>
        public static string Axles {
            get {
                return ResourceManager.GetString("Axles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branch Type.
        /// </summary>
        public static string BranchType_INDEX {
            get {
                return ResourceManager.GetString("BranchType_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car manufactures.
        /// </summary>
        public static string CarBrand_Title {
            get {
                return ResourceManager.GetString("CarBrand_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car models.
        /// </summary>
        public static string CarModel_Title {
            get {
                return ResourceManager.GetString("CarModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Car model types.
        /// </summary>
        public static string CarModelType_Title {
            get {
                return ResourceManager.GetString("CarModelType_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category Items TecDoc.
        /// </summary>
        public static string CategotyItemTecDoc {
            get {
                return ResourceManager.GetString("CategotyItemTecDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Categoty TecDoc.
        /// </summary>
        public static string CategotyTecDoc {
            get {
                return ResourceManager.GetString("CategotyTecDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Commercial vehicles.
        /// </summary>
        public static string CommercialVehicles {
            get {
                return ResourceManager.GetString("CommercialVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirmation.
        /// </summary>
        public static string Confirmation_TITLE {
            get {
                return ResourceManager.GetString("Confirmation_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete record ?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact Type.
        /// </summary>
        public static string ContactType_INDEX {
            get {
                return ResourceManager.GetString("ContactType_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target DB.
        /// </summary>
        public static string ContextName {
            get {
                return ResourceManager.GetString("ContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Country.
        /// </summary>
        public static string Country_INDEX {
            get {
                return ResourceManager.GetString("Country_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Currency.
        /// </summary>
        public static string Currency_INDEX {
            get {
                return ResourceManager.GetString("Currency_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string DetailTab {
            get {
                return ResourceManager.GetString("DetailTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string EditCommand {
            get {
                return ResourceManager.GetString("EditCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string EditTab {
            get {
                return ResourceManager.GetString("EditTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enterprise Addresses.
        /// </summary>
        public static string EnterpriseAddressTDES_INDEX {
            get {
                return ResourceManager.GetString("EnterpriseAddressTDES_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enterprise Branch Contacts.
        /// </summary>
        public static string EnterpriseBranchContactsTDES_INDEX {
            get {
                return ResourceManager.GetString("EnterpriseBranchContactsTDES_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enterprise Branches.
        /// </summary>
        public static string EnterpriseBranchTDES_INDEX {
            get {
                return ResourceManager.GetString("EnterpriseBranchTDES_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enterprise Branch User Contacts.
        /// </summary>
        public static string EnterpriseBranchUserContactTDES_INDEX {
            get {
                return ResourceManager.GetString("EnterpriseBranchUserContactTDES_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enterprise Branch Users.
        /// </summary>
        public static string EnterpriseBranchUserTDES_INDEX {
            get {
                return ResourceManager.GetString("EnterpriseBranchUserTDES_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enterprise Branch Work Places.
        /// </summary>
        public static string EnterpriseBranchWorkPlaceTDES_INDEX {
            get {
                return ResourceManager.GetString("EnterpriseBranchWorkPlaceTDES_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load (Unload) Enterprise Data.
        /// </summary>
        public static string EnterpriseDataLoadUnload {
            get {
                return ResourceManager.GetString("EnterpriseDataLoadUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enterprises.
        /// </summary>
        public static string EnterpriseNavigation_INDEX {
            get {
                return ResourceManager.GetString("EnterpriseNavigation_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product Category.
        /// </summary>
        public static string EnterpriseProductCategoryTDES_INDEX {
            get {
                return ResourceManager.GetString("EnterpriseProductCategoryTDES_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Supplier.
        /// </summary>
        public static string EnterpriseSupplier_INDEX {
            get {
                return ResourceManager.GetString("EnterpriseSupplier_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enterprise User Contact.
        /// </summary>
        public static string EnterpriseUserContactTDES_INDEX {
            get {
                return ResourceManager.GetString("EnterpriseUserContactTDES_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enterprise User.
        /// </summary>
        public static string EnterpriseUserNavigation_INDEX {
            get {
                return ResourceManager.GetString("EnterpriseUserNavigation_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FileName is empty.
        /// </summary>
        public static string Error_FileEmpty {
            get {
                return ResourceManager.GetString("Error_FileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Name is incorrect.
        /// </summary>
        public static string Error_FileIncorrect {
            get {
                return ResourceManager.GetString("Error_FileIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File not exists.
        /// </summary>
        public static string Error_FILENOTEXISTS {
            get {
                return ResourceManager.GetString("Error_FILENOTEXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Such File exists. ReWrite ?.
        /// </summary>
        public static string Error_FILEREWRITE {
            get {
                return ResourceManager.GetString("Error_FILEREWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process Is Broken.
        /// </summary>
        public static string Error_ProcessIsBroken {
            get {
                return ResourceManager.GetString("Error_ProcessIsBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process With Exception.
        /// </summary>
        public static string Error_ProcessWithException {
            get {
                return ResourceManager.GetString("Error_ProcessWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error_TITLE {
            get {
                return ResourceManager.GetString("Error_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From File.
        /// </summary>
        public static string FromFile {
            get {
                return ResourceManager.GetString("FromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From TecDoc.
        /// </summary>
        public static string FromTecDoc {
            get {
                return ResourceManager.GetString("FromTecDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fuel.
        /// </summary>
        public static string Fuel_Title {
            get {
                return ResourceManager.GetString("Fuel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get Max.
        /// </summary>
        public static string GetMax {
            get {
                return ResourceManager.GetString("GetMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation Is Done.
        /// </summary>
        public static string Info_OperationIsDone {
            get {
                return ResourceManager.GetString("Info_OperationIsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info.
        /// </summary>
        public static string Info_TITLE {
            get {
                return ResourceManager.GetString("Info_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In Process   .
        /// </summary>
        public static string InProcess_TITLE {
            get {
                return ResourceManager.GetString("InProcess_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        public static string InsertTab {
            get {
                return ResourceManager.GetString("InsertTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Boundary less than zero.
        /// </summary>
        public static string LessThanZero {
            get {
                return ResourceManager.GetString("LessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Item.
        /// </summary>
        public static string MakeSelection {
            get {
                return ResourceManager.GetString("MakeSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Motors.
        /// </summary>
        public static string Motors {
            get {
                return ResourceManager.GetString("Motors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        public static string NewCommand {
            get {
                return ResourceManager.GetString("NewCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   of  .
        /// </summary>
        public static string of_ITEMS {
            get {
                return ResourceManager.GetString("of_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation is not Implemented.
        /// </summary>
        public static string Operation_NotImplemented {
            get {
                return ResourceManager.GetString("Operation_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passenger Cars File Name.
        /// </summary>
        public static string PassengerCarsFile_TITLE {
            get {
                return ResourceManager.GetString("PassengerCarsFile_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh.
        /// </summary>
        public static string ReloadCommand {
            get {
                return ResourceManager.GetString("ReloadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string SaveCommand {
            get {
                return ResourceManager.GetString("SaveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settlement Type.
        /// </summary>
        public static string SettlementType_INDEX {
            get {
                return ResourceManager.GetString("SettlementType_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simple Types Load and Unload.
        /// </summary>
        public static string SimpleTypesLoadUnload_INDEX {
            get {
                return ResourceManager.GetString("SimpleTypesLoadUnload_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Soato.
        /// </summary>
        public static string Soato_INDEX {
            get {
                return ResourceManager.GetString("Soato_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Street Type.
        /// </summary>
        public static string StreetType_INDEX {
            get {
                return ResourceManager.GetString("StreetType_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TecDoc Src Type.
        /// </summary>
        public static string TecDocSrcType_INDEX {
            get {
                return ResourceManager.GetString("TecDocSrcType_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   to  .
        /// </summary>
        public static string to_ITEMS {
            get {
                return ResourceManager.GetString("to_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To File.
        /// </summary>
        public static string ToFile {
            get {
                return ResourceManager.GetString("ToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Undo.
        /// </summary>
        public static string UndoCommand {
            get {
                return ResourceManager.GetString("UndoCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Universals.
        /// </summary>
        public static string Universals {
            get {
                return ResourceManager.GetString("Universals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upper Boundary less than Lower.
        /// </summary>
        public static string UpperLessThanLower {
            get {
                return ResourceManager.GetString("UpperLessThanLower", resourceCulture);
            }
        }
    }
}
